# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CrossSectionDigitizer
                                 A QGIS plugin
 digitizer and georeferencer for 1D and 2D subsurface data 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-18
        copyright            : (C) 2025 by Cascadia Regional Earthquake Science Center (CRESCENT)
        email                : crescentcfm@cascadiaquakes.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CrossSectionDigitizer class from file CrossSectionDigitizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cross_section_digitizer import CrossSectionDigitizer
    return CrossSectionDigitizer(iface)
