name: Build and Release QGIS Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pb_tool and zip
      run: |
        python -m pip install --upgrade pip
        pip install pb_tool
        sudo apt-get update && sudo apt-get install -y zip

    - name: Build plugin with pb_tool
      run: pb_tool zip

    - name: Upload plugin .zip to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: zip_build/cross_section_digitizer.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}